### PR TITLE
Quick Fixes

### PR DESCRIPTION
**Pull request by LewdNeko**
- Wrong import order in main file.
- Don't use `!` as the prefix as it is overused.

### CODE REVIEW

**Comment by sco1** [comment]
Hi @LewdNeko, have you read this repository's [contribution guidelines](https://github.com/discord-python/hacktoberbot/blob/master/CONTRIBUTING.md)?

**Comment by LewdNeko** [comment]
I have indeed. I understand there is no staff created issue – thought I'd suggest some changes through a PR. Feel free to tag it `invalid`, close it, or do whatever you please.

**Comment by heavysaturn** [comment]
`h!` is a worse prefix. disregard for guidelines. we probably should set up some simple CI to lint with flake8 so import orders and so on will be solved and maintained with all future contributions, but I do not see the need for a PR for just changing an import order.

**Comment by heavysaturn** [comment]
addressed in #7. Closing PR.

**Pull request closed without merging**
